config/routes.rb
Rails.application.routes.draw do

  resources :notices
  resources :qnas
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  get 'user/index'

  get 'home/index'

  resources :products
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  get '/likes/:product_id/home' => 'home#like_product'
  get '/likes/:product_id/product' => 'products#like_product'
end

app/models/qna.rb
class Qna < ApplicationRecord
end

app/controllers/qnas_controller.rb
class QnasController < ApplicationController
  before_action :set_qna, only: [:show, :edit, :update, :destroy]

  # GET /qnas
  # GET /qnas.json
  def index
    @qnas = Qna.all
  end

  # GET /qnas/1
  # GET /qnas/1.json
  def show
  end

  # GET /qnas/new
  def new
    @qna = Qna.new
  end

  # GET /qnas/1/edit
  def edit
  end

  # POST /qnas
  # POST /qnas.json
  def create
    @qna = Qna.new(qna_params)

    respond_to do |format|
      if @qna.save
        format.html { redirect_to @qna, notice: 'Qna was successfully created.' }
        format.json { render :show, status: :created, location: @qna }
      else
        format.html { render :new }
        format.json { render json: @qna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qnas/1
  # PATCH/PUT /qnas/1.json
  def update
    respond_to do |format|
      if @qna.update(qna_params)
        format.html { redirect_to @qna, notice: 'Qna was successfully updated.' }
        format.json { render :show, status: :ok, location: @qna }
      else
        format.html { render :edit }
        format.json { render json: @qna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qnas/1
  # DELETE /qnas/1.json
  def destroy
    @qna.destroy
    respond_to do |format|
      format.html { redirect_to qnas_url, notice: 'Qna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qna
      @qna = Qna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qna_params
      params.require(:qna).permit(:user_name, :title, :content, :answer_email)
    end
end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/views/qnas/_form.html.erb
<%= form_for(qna) do |f| %>
  <% if qna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qna.errors.count, "error") %> prohibited this qna from being saved:</h2>

      <ul>
      <% qna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :answer_email %>
    <%= f.text_field :answer_email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qnas/edit.html.erb
<h1>Editing Qna</h1>

<%= render 'form', qna: @qna %>

<%= link_to 'Show', @qna %> |
<%= link_to 'Back', qnas_path %>

app/views/qnas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qnas</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Title</th>
      <th>Content</th>
      <th>Answer email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qnas.each do |qna| %>
      <tr>
        <td><%= qna.user_name %></td>
        <td><%= qna.title %></td>
        <td><%= qna.content %></td>
        <td><%= qna.answer_email %></td>
        <td><%= link_to 'Show', qna %></td>
        <td><%= link_to 'Edit', edit_qna_path(qna) %></td>
        <td><%= link_to 'Destroy', qna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qna', new_qna_path %>

app/views/qnas/new.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록하기</h1>
        </div>
        <div class="right">
          <h1>dashboard /</h1>
          <a href="#">page name</a>
        </div>
      </div>
      <!-- end head bottom -->
      
<h1>New qna</h1>

<%= render 'form', qna: @qna %>

<%= link_to 'Back', qnas_path %>

app/views/qnas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @qna.user_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @qna.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @qna.content %>
</p>

<p>
  <strong>Answer email:</strong>
  <%= @qna.answer_email %>
</p>

<%= link_to 'Edit', edit_qna_path(@qna) %> |
<%= link_to 'Back', qnas_path %>